//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerCentralsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductInfo
    {
        public string Farmer_Name { get; set; }
        public string Product_Name { get; set; }
        public string Product_Type_Name { get; set; }
        public Nullable<int> Quantity { get; set; }

        [Display(Name = "Price")]
        public int Price { get; set; }

        [Display(Name = "Best Before Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Best_Before_Date { get; set; }

        [Display(Name = "Date Received")]
        [DataType(DataType.Date)]
        
        public Nullable<System.DateTime> Date_Received { get; set; }

        [Display(Name = "Date Sold")]
        [DataType(DataType.Date)]
        
        public Nullable<System.DateTime> Date_Sold { get; set; }
    }
}
