//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerCentralsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tblEmployee
    {
        public int empId { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Employee Name")]
        public string empName { get; set; }

        [Display(Name = "Password")]
        [StringLength(30, MinimumLength = 8)]
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        public string password { get; set; }

        [Display(Name = "Confirm Password")]
        [StringLength(30, MinimumLength = 8)]
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("Password", ErrorMessage = "The two passwords do not match, please try again.")]
        public string confirmPassword { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Contact")]
        public string contact { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Address")]
        public string address { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Email Address")]
        public string emailAddress { get; set; }
    }
}
