//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerCentralsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblProduct
    {
        public int prodId { get; set; }
        public Nullable<int> farmerId { get; set; }
        public Nullable<int> prodTypeId { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Product Name")]
        public string prodName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Best Before Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> bestBeforeDate { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Price")]
        public int price { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Date Received")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> dateReceived { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Date Sold")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> dateSold { get; set; }
    
        public virtual tblFarmer tblFarmer { get; set; }
        public virtual tblProductType tblProductType { get; set; }
    }
}
